### ISSUE TITLE
 Missing Java version of fibonacci series 

### ISSUE THREAD

**Issue by Raksha003** [mekch01/STL-LIBRARY-#15]
There should be a java version for fibonacci series .

**Comment by Raksha003** [comment]
I want to work on this issue @mekch01.Please assign this to me

**Comment by mekch01** [comment]
You should fork my repo first then do whatever you want.

**Comment by Raksha003** [comment]
I did fork your repo but it has no option to create a new file  Sent from Mail for Windows From: mekch01Sent: 10 October 2021 10:15To: mekch01/STL-LIBRARY-Cc: Raksha.S; MentionSubject: Re: [mekch01/STL-LIBRARY-] Missing Java version of fibonacci series (#15) You should fork my repo first then do whatever you want.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Raksha003** [comment]
The same thing happened with implementation of stack but now it gives permission to add file .I shall wait for a few more minutes even for Fibonacci series. Sent from Mail for Windows From: mekch01Sent: 10 October 2021 10:27To: mekch01/STL-LIBRARY-Cc: Raksha.S; MentionSubject: Re: [mekch01/STL-LIBRARY-] Missing Java version of fibonacci series (#15) Don't Know why?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
